tap "alecthomas/tap"
tap "caskroom/cask"
tap "garden-io/garden"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "johanhaleby/kubetail"
tap "minio/stable"
tap "weaveworks/tap"
brew "openssl"
brew "ansible"
brew "awk"
brew "azure-cli"
brew "base64"
brew "bash"
brew "coreutils"
brew "docker-machine-driver-hyperkit"
brew "doctl"
brew "fluxctl"
brew "fzf"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "hcloud"
brew "icdiff"
brew "jq"
brew "kubernetes-cli"
brew "kubectx"
brew "kubernetes-helm"
brew "kustomize"
brew "make"
brew "mas"
brew "mkcert"
brew "mosh"
brew "neofetch"
brew "neovim"
brew "nmap"
brew "socat"
brew "openshift-cli"
brew "pinentry-mac"
brew "putty"
brew "pv"
brew "rsync"
brew "shellcheck"
brew "shfmt"
brew "skaffold"
brew "sops"
brew "telnet"
brew "tfenv"
brew "tmux"
brew "tree"
brew "velero", link: false
brew "watch"
brew "wget"
brew "youtube-dl"
brew "yq"
brew "zsh"
brew "zsh-completions"
brew "alecthomas/tap/gometalinter"
brew "garden-io/garden/garden-cli"
brew "johanhaleby/kubetail/kubetail", args: ["with-short-names"]
brew "minio/stable/minio"
brew "weaveworks/tap/eksctl"
cask "coconutbattery"
cask "keybase"
cask "minikube"
cask "minishift"
cask "vagrant"
cask "virtualbox"
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
