tap "alecthomas/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "awk"
brew "azure-cli"
brew "bash"
brew "coreutils"
brew "doctl"
brew "fzf"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "hcloud"
brew "jq"
brew "kustomize"
brew "mas"
brew "neovim"
brew "pinentry-mac"
brew "putty"
brew "shellcheck"
brew "zsh"
brew "alecthomas/tap/gometalinter"
cask "keybase"
cask "minikube"
cask "virtualbox"
mas "Amphetamine", id: 937984704
mas "Bear", id: 1091189122
mas "Magnet", id: 441258766
mas "Monosnap", id: 540348655
