[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"

[kubernetes]
disabled = true
style= "cyan bold"
format = 'on [⛵ $context \($namespace\)](purple) '
